# Generated by Django 4.0.3 on 2022-05-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='readers',
            field=models.ManyToManyField(related_name='story_readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to=settings.AUTH_USER_MODEL),
        ),
    ]
