# Generated by Django 4.0.3 on 2022-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_stories_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.FileField(upload_to='post/media/stories'),
        ),
    ]
